version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

    environment:
      DB_SOURCE: ${DB_URL}
volumes:
  pg_data:

networks:
  bank_net: